language: go

env:
  global:
    - GO111MODULE=on

before_script:
  - sudo install -d -o $USER -g $USER -m 0777 /images
  - go build

script:
  - go build
  - go test -cover ./...
  - ./tester.sh
  - ./textimg "t.png" -s
  - ./textimg "t.gif" -sa
  - [ -e /images/t.png ]
  - [ -e /images/t.gif ]
