version: '3'

services:
  textimg:
    build:
      context: ./
      dockerfile: ./build/textimg/Dockerfile
    image: jiro4989/textimg
    tty: true
    volumes:
      - "$PWD:/go/src/github.com/jiro4989/textimg"
      - "$PWD/images:/images"
