version: '3.7'

services:
  base:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: base
    container_name: textimg_base
    image: jiro4989/textimg-base
    working_dir: /go/src/github.com/jiro4989/textimg
    volumes:
      - "$PWD:/go/src/github.com/jiro4989/textimg"
      - "$PWD/images:/images"
    environment:
      - TEXTIMG_FONT_FILE=/tmp/MyricaM.TTC
      - TEXTIMG_EMOJI_DIR=/usr/local/src/noto-emoji/png/128
      - TEXTIMG_EMOJI_FONT_FILE=/tmp/Symbola_hint.ttf

  textimg:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: textimg
    image: jiro4989/textimg
    volumes:
      - "$PWD/images:/images"
