name: release

on:
  push:
    # tags:
    #   - 'v*.*.*'

env:
  app: textimg

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [386, amd64]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: Build
        run: |
          go build
          if [[ $GOOS = windows ]]; then
            7z a ${{ env.app }}-$GOOS-$GOARCH.zip ./${{ env.app }}.exe
          else
            tar czf ${{ env.app }}-$GOOS-$GOARCH.tar.gz ./${{ env.app }}
          fi
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload artifact (windows)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.app }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ env.app }}-${{ matrix.os }}-${{ matrix.arch }}.zip
        if: matrix.os == 'windows'

      - name: Upload artifact (unix)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.app }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ env.app }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        if: matrix.os != 'windows'
